site_name: IBM Maximo Asset Performance Management (APM) Labs
site_url: https://christophelucasibm.github.io/apmlabs/
site_author: Christophe Lucas
site_description: "IBM Maximo APM Hands on Labs"
nav:
    - Intro - Start Here: index.md
    - Monitor:
        - (MAS86) Discover Monitor with Pattern Files: monitor/monitor-patterns.md
        - (MAS83) Monitor on Maximo Application Suite & Saas: monitor/monitor.md
    - Health:
        - (MAS83) Health on Maximo Application Suite 8.3 [NEW]: health/health-mas.md
        - (MAHI) Maximo Asset Health Insights 7.6.1: health/health.md
    - Predict:
        - Predict on Maximo Application Suite [TBA]: predict/predict.md
    - Assist:
        - Assist on Maximo Application Suite [TBA]: assist/assist.md
    - (About, Feedback & Extras):
        - About & Feedback: about/about.md
        - Extras & Archive: extras/extras.md

# OLD (PRE MAY 2021 STRUCTURE)
#    - APM Labs:
#        - GET STARTED: index.md
#        - MONITOR: monitor/monitor.md
#        - HEALTH: health/health.md
#        - PREDICT: predict/predict.md
#        - ASSIST: assist/assist.md
#        - (About & Feedback): about/about.md
#        - (Extras & Archive): extras/extras.md        
    
# this is the base theme:
# theme: readthedocs

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition


# theme:
    # name: bootstrap

# theme: windmill
  
# theme:
  # name: null
  # custom_dir: 'cinder